[package]
name = "data-flow-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0",features = ["unstable"] }
futures-lite = "1.13.0"
tokio = { version = "1.27.0", features = ["sync"]}
serde = { version = "1.0.159", features = ["derive","rc"] }
serde_json = "1.0.95"
